AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: API Service of ECS on Fargate

Parameters:
  Project:
    Default: leone
    Type: String
    Description: Project Name
  Env:
    Default: dev
    Type: String
    Description: Environment Name

  DomainName:
    Type: String
    Description: Domain Name
  HostedZoneId:
    Type: String
    Description: Hosted Zone Id
  DockerImageTag:
    Type: String
    Description: Docker Image Tag

  TaskCPU:
    Type: String
    Description: CPU Size of ECS Task
  TaskMemory:
    Type: String
    Description: Memory Size of ECS Task

  AllowOrigin:
    Type: String
    Description: ALLOW_ORIGIN
  ClockFixed:
    Type: String
    Description: CLOCK_FIXED

Mappings:
  TaskDefinition:
    ap-northeast-1:
      Timezone: Asia/Tokyo

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/fargate/${Env}-${Project}-api'

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Env}-${Project}-api-task'
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref TaskCPU
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      TaskRoleArn:
        Fn::ImportValue: !Sub '${Env}-${Project}-ecs:task-role-arn'
      ExecutionRoleArn:
        Fn::ImportValue: !Sub '${Env}-${Project}-ecs:task-execution-role-arn'
      ContainerDefinitions:
        - Name: !Sub '${Env}-${Project}-api-container'
          Image: !Sub
            - '${RepositoryURL}:${DockerImageTag}'
            - RepositoryURL:
                Fn::ImportValue: !Sub '${Env}-${Project}-ecr:api-repository-uri'
              DockerImageTag: !Ref DockerImageTag
          PortMappings:
            - HostPort: 8080
              ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: !Sub '${Env}-${Project}-api'
          Environment:
            - Name: JAVA_OPTS
              Value: !Sub '-Dspring.profiles.active=${Env}'
            - Name: ALLOW_ORIGIN
              Value: !Ref AllowOrigin
            - Name: DB_JDBC_DRIVER
              Value: 'org.postgresql.Driver'
            - Name: DB_JDBC_URL
              Value: !Sub
                - 'jdbc:postgresql://${Host}:${Port}/${Database}'
                - Host: !Sub
                    - '{{resolve:secretsmanager:${Secret}:SecretString:host}}'
                    - Secret:
                        Fn::ImportValue: !Sub '${Env}-${Project}-rds:aurora-secret-arn'
                  Port: !Sub
                    - '{{resolve:secretsmanager:${Secret}:SecretString:port}}'
                    - Secret:
                        Fn::ImportValue: !Sub '${Env}-${Project}-rds:aurora-secret-arn'
                  Database: !Sub
                    - '{{resolve:secretsmanager:${Secret}:SecretString:dbname}}'
                    - Secret:
                        Fn::ImportValue: !Sub '${Env}-${Project}-rds:aurora-secret-arn'
            - Name: DB_USER
              Value: !Sub
                - '{{resolve:secretsmanager:${Secret}:SecretString:username}}'
                - Secret:
                    Fn::ImportValue: !Sub '${Env}-${Project}-rds:aurora-secret-arn'
            - Name: DB_PASSWORD
              Value: !Sub
                - '{{resolve:secretsmanager:${Secret}:SecretString:password}}'
                - Secret:
                    Fn::ImportValue: !Sub '${Env}-${Project}-rds:aurora-secret-arn'
            - Name: CLOCK_FIXED
              Value: !Ref ClockFixed
            - Name: CLOCK_TIME_ZONE
              Value: !FindInMap [TaskDefinition, !Ref AWS::Region, Timezone]
            - Name: AWS_DEFAULT_REGION
              Value: !Ref AWS::Region
            - Name: S3_ENDPOINT_URL
              Value: !Sub 'https://s3.${AWS::Region}.amazonaws.com'
            - Name: S3_DATA_BUCKET
              Value:
                Fn::ImportValue: !Sub '${Env}-${Project}-s3:data-bucket-name'
            - Name: COGNITO_USER_POOL_ID
              Value:
                Fn::ImportValue: !Sub '${Env}-${Project}-cognito:user-pool-id'
            - Name: COGNITO_CLIENT_ID
              Value:
                Fn::ImportValue: !Sub '${Env}-${Project}-cognito:user-pool-client-id'

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${Env}-${Project}-api-alb'
      IpAddressType: ipv4
      Scheme: internet-facing
      Type: application
      Subnets: !Split
        - ','
        - Fn::ImportValue: !Sub '${Env}-${Project}-vpc:public-subnet-ids'
      SecurityGroups:
        - Fn::ImportValue: !Sub '${Env}-${Project}-security-group:public-security-group-id'
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${Project}-api-alb'

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${Env}-${Project}-api-tg'
      VpcId:
        Fn::ImportValue: !Sub '${Env}-${Project}-vpc:id'
      Protocol: HTTP
      Port: 80
      TargetType: ip
      Matcher:
        HttpCode: 200
      HealthCheckPath: /actuator/health
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 300
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${Project}-api-tg'

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - ApplicationLoadBalancer
      - TargetGroup
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTPS
      Port: 443
      SslPolicy: 'ELBSecurityPolicy-TLS-1-2-2017-01'
      Certificates:
        - CertificateArn:
            Fn::ImportValue: !Sub '${Env}-${Project}-certificate-manager:certificate-arn'
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ARecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - ApplicationLoadBalancer
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref HostedZoneId
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID

  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - ApplicationLoadBalancer
      - ECSTaskDefinition
    Properties:
      Cluster:
        Fn::ImportValue: !Sub '${Env}-${Project}-ecs:cluster-arn'
      ServiceName: !Sub '${Env}-${Project}-api-service'
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref ECSTaskDefinition
      LoadBalancers:
        - ContainerName: !Sub '${Env}-${Project}-api-container'
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub '${Env}-${Project}-security-group:ecs-api-security-group-id'
          Subnets: !Split
            - ','
            - Fn::ImportValue: !Sub '${Env}-${Project}-vpc:public-subnet-ids'

Outputs:
  LogGroupArn:
    Value: !GetAtt LogGroup.Arn
    Export:
      Name: !Sub '${AWS::StackName}-log-group-arn'

  ECSTaskDefinitionArn:
    Value: !Ref ECSTaskDefinition
    Export:
      Name: !Sub '${AWS::StackName}-ecs-task-definition-arn'

  ApplicationLoadBalancerArn:
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub '${AWS::StackName}-alb-arn'
  ApplicationLoadBalancerDNSName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${AWS::StackName}-alb-dns-name'
  ApplicationLoadBalancerHostedZoneId:
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub '${AWS::StackName}-alb-hosted-zone-id'
  ApplicationLoadBalancerFullName:
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
    Export:
      Name: !Sub '${AWS::StackName}-alb-full-name'
  ApplicationLoadBalancerName:
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerName
    Export:
      Name: !Sub '${AWS::StackName}-alb-name'

  TargetGroupArn:
    Value: !Ref TargetGroup
    Export:
      Name: !Sub '${AWS::StackName}-tg-arn'
  TargetGroupFullName:
    Value: !GetAtt TargetGroup.TargetGroupFullName
    Export:
      Name: !Sub '${AWS::StackName}-tg-full-name'
  TargetGroupName:
    Value: !GetAtt TargetGroup.TargetGroupName
    Export:
      Name: !Sub '${AWS::StackName}-tg-name'

  ECSServiceArn:
    Value: !Ref ECSService
    Export:
      Name: !Sub '${AWS::StackName}-ecs-service-arn'
  ECSServiceName:
    Value: !GetAtt ECSService.Name
    Export:
      Name: !Sub '${AWS::StackName}-ecs-service-name'
