AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBClusterIdentifier:
    Type: String
  DBClusterParameterGroupName:
    Type: String
  DBSubnetGroupName:
    Type: String
  Engine:
    Type: String
  EngineVersion:
    Type: String
  DatabaseName:
    Type: String
  MasterUsername:
    Type: String
  Port:
    Type: String
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${DBClusterIdentifier}-secret'
      Description: !Sub '${DBClusterIdentifier}-secret'
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${MasterUsername}"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        IncludeSpace: false
        ExcludePunctuation: true

  DBCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
      - Secret
    Properties:
      DBClusterIdentifier: !Ref DBClusterIdentifier
      DBClusterParameterGroupName: !Ref DBClusterParameterGroupName
      DBSubnetGroupName: !Ref DBSubnetGroupName
      Engine: !Ref Engine
      EngineMode: provisioned
      EngineVersion: !Ref EngineVersion
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Sub '{{resolve:secretsmanager:${Secret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${Secret}:SecretString:password}}'
      Port: !Ref Port
      BackupRetentionPeriod: 7
      StorageEncrypted: true
      PreferredBackupWindow: '18:00-18:30'
      PreferredMaintenanceWindow: 'Sat:19:00-Sat:19:30'
      VpcSecurityGroupIds:
        - !Ref SecurityGroupId
    DeletionPolicy: Delete

  SecretTargetAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    DependsOn:
      - Secret
      - DBCluster
    Properties:
      SecretId: !Ref Secret
      TargetId: !Ref DBCluster
      TargetType: AWS::RDS::DBCluster

Outputs:
  SecretArn:
    Value: !Ref Secret

  DBClusterId:
    Value: !Ref DBCluster

  DBClusterArn:
    Value: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${DBCluster}'
