AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  Engine:
    Type: String
  EngineVersion:
    Type: String
  DBClusterIdentifier:
    Type: String
  DBInstanceIdentifier:
    Type: String
  DBInstanceClass:
    Type: String
  DBParameterGroupName:
    Type: String
  DBSubnetGroupName:
    Type: String

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      DBClusterIdentifier: !Ref DBClusterIdentifier
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: !Ref DBInstanceClass
      DBParameterGroupName: !Ref DBParameterGroupName
      DBSubnetGroupName: !Ref DBSubnetGroupName
      PubliclyAccessible: false
