AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Name:
    Type: String
  Description:
    Type: String
  SubnetIds:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Ref Name
      DBSubnetGroupDescription: !Ref Description
      SubnetIds: !Split
        - ','
        - !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Ref Name

Outputs:
  DBSubnetGroupId:
    Value: !Ref DBSubnetGroup
