AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Username:
    Type: String
  UserPoolId:
    Type: String

Resources:
  UserPoolUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      ForceAliasCreation: true
      MessageAction: SUPPRESS
      UserAttributes:
        - Name: email
          Value: !Ref Username
        - Name: email_verified
          Value: True
      Username: !Ref Username
      UserPoolId: !Ref UserPoolId
