AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecretName:
    Type: String
  Username:
    Type: String
  UserPoolId:
    Type: String

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: !Ref SecretName
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${Username}"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        IncludeSpace: false
        ExcludeCharacters: "\"'"

  UserPoolUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      ForceAliasCreation: true
      MessageAction: SUPPRESS
      UserAttributes:
        - Name: email
          Value: !Ref Username
        - Name: email_verified
          Value: True
      Username: !Ref Username
      UserPoolId: !Ref UserPoolId

Outputs:
  SecretArn:
    Value: !Ref Secret
