AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Cognito

Parameters:
  Project:
    Type: String
  Env:
    Type: String

  AdministratorEmail:
    Type: String

Resources:
  UserPool:
    Type: AWS::Serverless::Application
    Properties:
      Location: user-pool.yaml
      Parameters:
        UserPoolName: !Sub '${Env}-${Project}-user-pool'

  UserPoolClient:
    Type: AWS::Serverless::Application
    Properties:
      Location: user-pool-client.yaml
      Parameters:
        ClientName: !Sub '${Env}-${Project}-user-pool-client'
        UserPoolId: !GetAtt UserPool.Outputs.UserPoolId

  AdministratorUser:
    Type: AWS::Serverless::Application
    Properties:
      Location: administrator-user.yaml
      Parameters:
        SecretName: !Sub '${Env}-${Project}-cognito-administrator-user-secret'
        Username: !Ref AdministratorEmail
        UserPoolId: !GetAtt UserPool.Outputs.UserPoolId

Outputs:
  UserPoolId:
    Value: !GetAtt UserPool.Outputs.UserPoolId

  UserPoolArn:
    Value: !GetAtt UserPool.Outputs.UserPoolArn

  UserPoolClientId:
    Value: !GetAtt UserPoolClient.Outputs.UserPoolClientId

  AdministratorUserSecretArn:
    Value: !GetAtt AdministratorUser.Outputs.SecretArn
