AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  RepositoryName:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: IMMUTABLE

Outputs:
  RepositoryArn:
    Value: !GetAtt Repository.Arn

  RepositoryUri:
    Value: !GetAtt Repository.RepositoryUri
