AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: ECR

Parameters:
  Project:
    Type: String
  Env:
    Type: String

Resources:
  ApiRepository:
    Type: AWS::Serverless::Application
    Properties:
      Location: repository.yaml
      Parameters:
        RepositoryName: !Sub '${Env}-${Project}-api'

  WebRepository:
    Type: AWS::Serverless::Application
    Properties:
      Location: repository.yaml
      Parameters:
        RepositoryName: !Sub '${Env}-${Project}-web'

  BatchRepository:
    Type: AWS::Serverless::Application
    Properties:
      Location: repository.yaml
      Parameters:
        RepositoryName: !Sub '${Env}-${Project}-batch'

Outputs:
  ApiRepositoryArn:
    Value: !GetAtt ApiRepository.Outputs.RepositoryArn
  ApiRepositoryUri:
    Value: !GetAtt ApiRepository.Outputs.RepositoryUri

  WebRepositoryArn:
    Value: !GetAtt WebRepository.Outputs.RepositoryArn
  WebRepositoryUri:
    Value: !GetAtt WebRepository.Outputs.RepositoryUri

  BatchRepositoryArn:
    Value: !GetAtt BatchRepository.Outputs.RepositoryArn
  BatchRepositoryUri:
    Value: !GetAtt BatchRepository.Outputs.RepositoryUri
