AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: ECS

Parameters:
  Project:
    Type: String
  Env:
    Type: String

  BucketArn:
    Type: String
  UserPoolArn:
    Type: String

Resources:
  ECSCluster:
    Type: AWS::Serverless::Application
    Properties:
      Location: cluster.yaml
      Parameters:
        ClusterName: !Sub '${Env}-${Project}-cluster'

  ECSTaskExecutionRole:
    Type: AWS::Serverless::Application
    Properties:
      Location: task-execution-role.yaml
      Parameters:
        RoleName: !Sub '${Env}-${Project}-ecs-task-exec-role'

  ECSTaskRole:
    Type: AWS::Serverless::Application
    Properties:
      Location: task-role.yaml
      Parameters:
        RoleName: !Sub '${Env}-${Project}-ecs-task-role'
        BucketArn: !Ref BucketArn
        UserPoolArn: !Ref UserPoolArn

  ECSServiceAutoScalingRole:
    Type: AWS::Serverless::Application
    Properties:
      Location: service-auto-scaling-role.yaml
      Parameters:
        RoleName: !Sub '${Env}-${Project}-ecs-svc-as-role'

Outputs:
  ECSClusterName:
    Value: !GetAtt ECSCluster.Outputs.ClusterName

  ECSClusterArn:
    Value: !GetAtt ECSCluster.Outputs.ClusterArn

  ECSTaskExecutionRoleArn:
    Value: !GetAtt ECSTaskExecutionRole.Outputs.RoleArn

  ECSTaskRoleArn:
    Value: !GetAtt ECSTaskRole.Outputs.RoleArn

  ECSServiceAutoScalingRoleArn:
    Value: !GetAtt ECSServiceAutoScalingRole.Outputs.RoleArn
