AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3

Parameters:
  Project:
    Type: String
  Env:
    Type: String

Resources:
  DataBucket:
    Type: AWS::Serverless::Application
    Properties:
      Location: data-bucket.yaml
      Parameters:
        BucketName: !Sub '${Env}-${Project}-data'

Outputs:
  DataBucketName:
    Value: !GetAtt DataBucket.Outputs.BucketName

  DataBucketArn:
    Value: !GetAtt DataBucket.Outputs.BucketArn
