AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  EC2ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  DataBucketArn:
    Type: String
  UserPoolArn:
    Type: String
  AuroraClusterArn:
    Type: String

  BastionName:
    Type: String
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${BastionName}-role'
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource:
                  - !Ref DataBucketArn
                  - !Sub '${DataBucketArn}/*'
        - PolicyName: Cognito
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: cognito-idp:*
                Resource:
                  - !Ref UserPoolArn
        - PolicyName: RDS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: rds:*
                Resource:
                  - !Ref AuroraClusterArn

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${BastionName}-instance-profile'
      Path: '/'
      Roles:
        - !Ref Role

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "${BastionName}-eip"

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2ImageId
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          Description: !Sub '${BastionName}-ssh'
          DeviceIndex: '0'
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref SecurityGroupId
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash -xe
          sudo yum update -y
          yum install -y aws-cfn-bootstrap
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      Tags:
        - Key: Name
          Value: !Ref BastionName

  BastionEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    DependsOn:
      - EIP
      - Instance
    Properties:
      InstanceId: !Ref Instance
      EIP: !Ref EIP

Outputs:
  EIP:
    Value: !GetAtt EIP.AllocationId
