AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: EC2

Parameters:
  Project:
    Type: String
  Env:
    Type: String

  EC2ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  DataBucketArn:
    Type: String
  UserPoolArn:
    Type: String
  AuroraClusterArn:
    Type: String

  BastionKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  BastionSubnetId:
    Type: AWS::EC2::Subnet::Id
  BastionSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  Bastion:
    Type: AWS::Serverless::Application
    Properties:
      Location: bastion.yaml
      Parameters:
        DataBucketArn: !Ref DataBucketArn
        UserPoolArn: !Ref UserPoolArn
        AuroraClusterArn: !Ref AuroraClusterArn
        BastionName: !Sub '${Env}-${Project}-bastion'
        KeyPairName: !Ref BastionKeyPairName
        SubnetId: !Ref BastionSubnetId
        SecurityGroupId: !Ref BastionSecurityGroupId

Outputs:
  BastionEIP:
    Value: !GetAtt Bastion.Outputs.EIP
