AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  EIPName:
    Type: String

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Ref EIPName

Outputs:
  AllocationId:
    Value: !GetAtt EIP.AllocationId
