AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  NatGatewayName:
    Type: String
  AllocationId:
    Type: String
  SubnetId:
    Type: AWS::EC2::Subnet::Id

Resources:
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !Ref AllocationId
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Ref NatGatewayName

Outputs:
  NatGatewayId:
    Value: !Ref NatGateway
