AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  NetworkAclId:
    Type: String

Resources:
  NetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref SubnetId
      NetworkAclId: !Ref NetworkAclId
