AWSTemplateFormatVersion: 2010-09-09
Description: RDS

Parameters:
  Project:
    Default: leone
    Type: String
    Description: Project Name
  Env:
    Default: dev
    Type: String
    Description: Environment Name

  VPCStackName:
    Type: String
    Description: Stack Name of VPC
  SecurityGroupStackName:
    Type: String
    Description: Stack Name of SecurityGroup

  DatabaseName:
    Type: String
    Description: Database Name
  DatabaseUser:
    Type: String
    Description: Database User Name
  DatabasePassword:
    NoEcho: true
    Type: String
    Description: Database Password

Mappings:
  Aurora:
    General:
      Family: aurora-postgresql13
      Engine: aurora-postgresql
      EngineVersion: 13.4
      Port: 5432
    ap-northeast-1:
      Timezone: Asia/Tokyo
    dev:
      InstanceClass: db.t3.medium
    stg:
      InstanceClass: db.t3.medium
    prod:
      InstanceClass: db.t3.medium

Resources:
  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${Env}-${Project}-aurora-sng"
      DBSubnetGroupDescription: !Sub "${Env}-${Project}-aurora-sng"
      SubnetIds:
        - Fn::ImportValue: !Sub "${VPCStackName}-private-subnet-a-id"
        - Fn::ImportValue: !Sub "${VPCStackName}-private-subnet-c-id"
        - Fn::ImportValue: !Sub "${VPCStackName}-private-subnet-d-id"
      Tags:
        - Key: Name
          Value: !Sub "${Env}-${Project}-aurora-sng"

  AuroraClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub "${Env}-${Project}-aurora-cluster-pg"
      Family: !FindInMap [Aurora, General, Family]
      Parameters:
        timezone: !FindInMap [Aurora, !Ref AWS::Region, Timezone]

  AuroraDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub "${Env}-${Project}-aurora-db-pg"
      Family: !FindInMap [Aurora, General, Family]

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub "${Env}-${Project}-cluster"
      DBClusterParameterGroupName: !Ref AuroraClusterParameterGroup
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      Engine: !FindInMap [Aurora, General, Engine]
      EngineMode: provisioned
      EngineVersion: !FindInMap [Aurora, General, EngineVersion]
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      Port: !FindInMap [Aurora, General, Port]
      BackupRetentionPeriod: 7
      StorageEncrypted: true
      PreferredBackupWindow: "18:00-18:30"
      PreferredMaintenanceWindow: "Sat:19:00-Sat:19:30"
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub "${SecurityGroupStackName}-aurora-sg-id"

  AuroraInstanceA01:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      Engine: !FindInMap [Aurora, General, Engine]
      EngineVersion: !FindInMap [Aurora, General, EngineVersion]
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceIdentifier: !Sub "${Env}-${Project}-db-a01"
      DBInstanceClass: !FindInMap [Aurora, !Ref Env, InstanceClass]
      DBParameterGroupName: !Ref AuroraDBParameterGroup
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  AuroraInstanceC01:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}c"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      Engine: !FindInMap [Aurora, General, Engine]
      EngineVersion: !FindInMap [Aurora, General, EngineVersion]
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceIdentifier: !Sub "${Env}-${Project}-db-c01"
      DBInstanceClass: !FindInMap [Aurora, !Ref Env, InstanceClass]
      DBParameterGroupName: !Ref AuroraDBParameterGroup
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  AuroraInstanceD01:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}d"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      Engine: !FindInMap [Aurora, General, Engine]
      EngineVersion: !FindInMap [Aurora, General, EngineVersion]
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceIdentifier: !Sub "${Env}-${Project}-db-d01"
      DBInstanceClass: !FindInMap [Aurora, !Ref Env, InstanceClass]
      DBParameterGroupName: !Ref AuroraDBParameterGroup
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

Outputs:
  AuroraSubnetGroupID:
    Value: !Ref AuroraSubnetGroup
    Export:
      Name: !Sub "${AWS::StackName}-aurora-sng-id"

  AuroraClusterParameterGroupID:
    Value: !Ref AuroraClusterParameterGroup
    Export:
      Name: !Sub "${AWS::StackName}-aurora-cluster-pg-id"
  AuroraDBParameterGroupID:
    Value: !Ref AuroraDBParameterGroup
    Export:
      Name: !Sub "${AWS::StackName}-aurora-db-pg-id"

  DatabaseName:
    Value: !Ref DatabaseName
    Export:
      Name: !Sub "${AWS::StackName}-database-name"
  DatabaseUser:
    Value: !Ref DatabaseUser
    Export:
      Name: !Sub "${AWS::StackName}-database-user"
  DatabasePassword:
    Value: !Ref DatabasePassword
    Export:
      Name: !Sub "${AWS::StackName}-database-password"

  AuroraClusterId:
    Value: !Ref AuroraCluster
    Export:
      Name: !Sub "${AWS::StackName}-aurora-cluster-id"
  AuroraClusterArn:
    Value: !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AuroraCluster}"
    Export:
      Name: !Sub "${AWS::StackName}-aurora-cluster-arn"
  AuroraEndpointURL:
    Value: !GetAtt AuroraCluster.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-aurora-endpoint-url"
  AuroraEndpointPort:
    Value: !GetAtt AuroraCluster.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-aurora-endpoint-port"
  AuroraReadEndpointURL:
    Value: !GetAtt AuroraCluster.ReadEndpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-aurora-read-endpoint-url"

  AuroraInstanceA01Id:
    Value: !Ref AuroraInstanceA01
    Export:
      Name: !Sub "${AWS::StackName}-db-a01-id"
  AuroraInstanceA01Arn:
    Value: !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${AuroraInstanceA01}"
    Export:
      Name: !Sub "${AWS::StackName}-db-a01-arn"
  AuroraInstanceA01EndpointURL:
    Value: !GetAtt AuroraInstanceA01.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-db-a01-endpoint-url"
  AuroraInstanceA01EndpointPort:
    Value: !GetAtt AuroraInstanceA01.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-db-a01-endpoint-port"

  AuroraInstanceC01Id:
    Value: !Ref AuroraInstanceC01
    Export:
      Name: !Sub "${AWS::StackName}-db-c01-id"
  AuroraInstanceC01Arn:
    Value: !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${AuroraInstanceC01}"
    Export:
      Name: !Sub "${AWS::StackName}-db-c01-arn"
  AuroraInstanceC01EndpointURL:
    Value: !GetAtt AuroraInstanceC01.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-db-c01-endpoint-url"
  AuroraInstanceC01EndpointPort:
    Value: !GetAtt AuroraInstanceC01.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-db-c01-endpoint-port"

  AuroraInstanceD01Id:
    Value: !Ref AuroraInstanceD01
    Export:
      Name: !Sub "${AWS::StackName}-db-d01-id"
  AuroraInstanceD01Arn:
    Value: !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:${AuroraInstanceD01}"
    Export:
      Name: !Sub "${AWS::StackName}-db-d01-arn"
  AuroraInstanceD01EndpointURL:
    Value: !GetAtt AuroraInstanceD01.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-db-d01-endpoint-url"
  AuroraInstanceD01EndpointPort:
    Value: !GetAtt AuroraInstanceD01.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-db-d01-endpoint-port"
