AWSTemplateFormatVersion: 2010-09-09
Description: S3

Parameters:
  Project:
    Default: leone
    Type: String
    Description: Project Name
  Env:
    Default: dev
    Type: String
    Description: Environment Name

  LambdaFunctionsBucketName:
    Type: String
    Description: Lambda Functions Bucket Name
  DataBucketName:
    Type: String
    Description: Data Bucket Name

Resources:
  LambdaFunctionsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LambdaFunctionsBucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DataBucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      CorsConfiguration:
        CorsRules:
          - Id: PreSignedURLRule
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            MaxAge: 3600

Outputs:
  LambdaFunctionsBucketName:
    Value: !Ref LambdaFunctionsBucket
    Export:
      Name: !Sub "${AWS::StackName}-lambda-functions-bucket-name"
  LambdaFunctionsBucketArn:
    Value: !GetAtt LambdaFunctionsBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-lambda-functions-bucket-arn"

  DataBucketName:
    Value: !Ref DataBucket
    Export:
      Name: !Sub "${AWS::StackName}-data-bucket-name"
  DataBucketArn:
    Value: !GetAtt DataBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-data-bucket-arn"
