AWSTemplateFormatVersion: 2010-09-09
Description: S3

Parameters:
  Project:
    Default: leone
    Type: String
    Description: Project Name
  Env:
    Default: dev
    Type: String
    Description: Environment Name

  DataBucketName:
    Type: String
    Description: Data Bucket Name

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DataBucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      CorsConfiguration:
        CorsRules:
          - Id: PreSignedURLRule
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            MaxAge: 3600

Outputs:
  DataBucketName:
    Value: !Ref DataBucket
    Export:
      Name: !Sub "${AWS::StackName}-data-bucket-name"
  DataBucketArn:
    Value: !GetAtt DataBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-data-bucket-arn"
