AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Project:
    Type: String
    Description: Project Name
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment Name

  CIDR:
    Type: String
    Description: CIDR Block

  PublicSubnetCIDRA:
    Type: String
    Description: Public Subnet CIDR Block AZ-A
  PublicSubnetCIDRC:
    Type: String
    Description: Public Subnet CIDR Block AZ-C
  PublicSubnetCIDRD:
    Type: String
    Description: Public Subnet CIDR Block AZ-D

  PrivateSubnetCIDRA:
    Type: String
    Description: Private Subnet CIDR Block AZ-A
  PrivateSubnetCIDRC:
    Type: String
    Description: Private Subnet CIDR Block AZ-C
  PrivateSubnetCIDRD:
    Type: String
    Description: Private Subnet CIDR Block AZ-D

  HostedZoneId:
    Type: String
    Description: Hosted Zone Id
  DomainName:
    Type: String
    Description: Domain Name

  AdministratorEmail:
    Type: String
    Description: Administrator User Email

  DatabaseName:
    Type: String
    Description: Database Name
  MasterUsername:
    Type: String
    Description: Database Master User Name

Resources:
  VPCStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc/template.yaml
      Parameters:
        Project: !Ref Project
        Env: !Ref Env
        CIDR: !Ref CIDR
        PublicSubnetCIDRA: !Ref PublicSubnetCIDRA
        PublicSubnetCIDRC: !Ref PublicSubnetCIDRC
        PublicSubnetCIDRD: !Ref PublicSubnetCIDRD
        PrivateSubnetCIDRA: !Ref PrivateSubnetCIDRA
        PrivateSubnetCIDRC: !Ref PrivateSubnetCIDRC
        PrivateSubnetCIDRD: !Ref PrivateSubnetCIDRD

  SecurityGroupStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - VPCStack
    Properties:
      Location: security-group/template.yaml
      Parameters:
        Project: !Ref Project
        Env: !Ref Env
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetCIDRA: !Ref PublicSubnetCIDRA
        PublicSubnetCIDRC: !Ref PublicSubnetCIDRC
        PublicSubnetCIDRD: !Ref PublicSubnetCIDRD
        PrivateSubnetCIDRA: !Ref PrivateSubnetCIDRA
        PrivateSubnetCIDRC: !Ref PrivateSubnetCIDRC
        PrivateSubnetCIDRD: !Ref PrivateSubnetCIDRD

  CertificateManagerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: certificate-manager/template.yaml
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        DomainName: !Ref DomainName

  ECRStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ecr/template.yaml
      Parameters:
        Project: !Ref Project
        Env: !Ref Env

  S3Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3/template.yaml
      Parameters:
        Project: !Ref Project
        Env: !Ref Env

  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito/template.yaml
      Parameters:
        Project: !Ref Project
        Env: !Ref Env
        AdministratorEmail: !Ref AdministratorEmail

  RDSStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - VPCStack
      - SecurityGroupStack
    Properties:
      Location: rds/template.yaml
      Parameters:
        Project: !Ref Project
        Env: !Ref Env
        PrivateSubnetIds: !GetAtt VPCStack.Outputs.PrivateSubnetIds
        AuroraSecurityGroupId: !GetAtt SecurityGroupStack.Outputs.AuroraSecurityGroupId
        DatabaseName: !Ref DatabaseName
        MasterUsername: !Ref MasterUsername

  ECSStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - S3Stack
      - CognitoStack
    Properties:
      Location: ecs/template.yaml
      Parameters:
        Project: !Ref Project
        Env: !Ref Env
        BucketArn: !GetAtt S3Stack.Outputs.DataBucketArn
        UserPoolArn: !GetAtt CognitoStack.Outputs.UserPoolArn

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Export:
      Name: !Sub '${Env}-${Project}-vpc:id'

  PublicSubnetIds:
    Value: !GetAtt VPCStack.Outputs.PublicSubnetIds
    Export:
      Name: !Sub '${Env}-${Project}-vpc:public-subnet-ids'

  PrivateSubnetIds:
    Value: !GetAtt VPCStack.Outputs.PrivateSubnetIds
    Export:
      Name: !Sub '${Env}-${Project}-vpc:private-subnet-ids'

  PublicSecurityGroupId:
    Value: !GetAtt SecurityGroupStack.Outputs.PublicSecurityGroupId
    Export:
      Name: !Sub '${Env}-${Project}-security-group:public-security-group-id'

  ECSWebSecurityGroupId:
    Value: !GetAtt SecurityGroupStack.Outputs.ECSWebSecurityGroupId
    Export:
      Name: !Sub '${Env}-${Project}-security-group:ecs-web-security-group-id'

  ECSAPISecurityGroupId:
    Value: !GetAtt SecurityGroupStack.Outputs.ECSAPISecurityGroupId
    Export:
      Name: !Sub '${Env}-${Project}-security-group:ecs-api-security-group-id'

  CertificateArn:
    Value: !GetAtt CertificateManagerStack.Outputs.CertificateArn
    Export:
      Name: !Sub '${Env}-${Project}-certificate-manager:certificate-arn'

  WebRepositoryUri:
    Value: !GetAtt ECRStack.Outputs.WebRepositoryUri
    Export:
      Name: !Sub '${Env}-${Project}-ecr:web-repository-uri'

  ApiRepositoryUri:
    Value: !GetAtt ECRStack.Outputs.ApiRepositoryUri
    Export:
      Name: !Sub '${Env}-${Project}-ecr:api-repository-uri'

  BatchRepositoryUri:
    Value: !GetAtt ECRStack.Outputs.BatchRepositoryUri
    Export:
      Name: !Sub '${Env}-${Project}-ecr:batch-repository-uri'

  DataBucketName:
    Value: !GetAtt S3Stack.Outputs.DataBucketName
    Export:
      Name: !Sub '${Env}-${Project}-s3:data-bucket-name'

  CognitoUserPoolId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolId
    Export:
      Name: !Sub '${Env}-${Project}-cognito:user-pool-id'

  UserPoolClientId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId
    Export:
      Name: !Sub '${Env}-${Project}-cognito:user-pool-client-id'

  AuroraSecretArn:
    Value: !GetAtt RDSStack.Outputs.AuroraSecretArn
    Export:
      Name: !Sub '${Env}-${Project}-rds:aurora-secret-arn'

  ECSClusterName:
    Value: !GetAtt ECSStack.Outputs.ECSClusterName
    Export:
      Name: !Sub '${Env}-${Project}-ecs:cluster-name'

  ECSClusterArn:
    Value: !GetAtt ECSStack.Outputs.ECSClusterArn
    Export:
      Name: !Sub '${Env}-${Project}-ecs:cluster-arn'

  ECSTaskExecutionRoleArn:
    Value: !GetAtt ECSStack.Outputs.ECSTaskExecutionRoleArn
    Export:
      Name: !Sub '${Env}-${Project}-ecs:task-execution-role-arn'

  ECSTaskRoleArn:
    Value: !GetAtt ECSStack.Outputs.ECSTaskRoleArn
    Export:
      Name: !Sub '${Env}-${Project}-ecs:task-role-arn'

  ECSServiceAutoScalingRoleArn:
    Value: !GetAtt ECSStack.Outputs.ECSServiceAutoScalingRoleArn
    Export:
      Name: !Sub '${Env}-${Project}-ecs:service-auto-scaling-role-arn'